### ISSUE TITLE
Thread 'main' panicked at 'Trick: if you are running on a vm' when machine is not a VM

### ISSUE THREAD

**Issue by DavidMChan** [hubblo-org/scaphandre#131]
## Bug description

Running scaphandre on bare metal (no VM) produces the following error, even though the machine is not a virtual machine:
```
Scaphandre stdout exporter
Sending ⚡ metrics
thread 'main' panicked at 'Trick: if you are running on a vm, do not forget to use --vm parameter invoking scaphandre at the command line', src/sensors/mod.rs:263:18
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/option.rs:1292:5
   3: core::option::Option<T>::expect
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/option.rs:349:21
   4: scaphandre::sensors::Topology::add_cpu_cores
             at ./src/sensors/mod.rs:259:26
   5: <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::generate_topology
             at ./src/sensors/powercap_rapl.rs:106:9
   6: <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::get_topology
             at ./src/sensors/powercap_rapl.rs:112:24
   7: scaphandre::exporters::stdout::StdoutExporter::runner
             at ./src/exporters/stdout.rs:122:24
   8: <scaphandre::exporters::stdout::StdoutExporter as scaphandre::exporters::Exporter>::run
             at ./src/exporters/stdout.rs:19:9
   9: scaphandre::run
             at ./src/lib.rs:74:9
  10: scaphandre::main
             at ./src/main.rs:81:5
  11: core::ops::function::FnOnce::call_once
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Adding the "--vm" argument gives (and still does not work):
```
scaphandre::sensors::powercap_rapl: Powercap_rapl path is: /var/scaphandre
Scaphandre stdout exporter
Sending ⚡ metrics
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/sensors/powercap_rapl.rs:76:53
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/result.rs:1284:5
   3: core::result::Result<T,E>::unwrap
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/result.rs:1037:23
   4: <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::generate_topology
             at ./src/sensors/powercap_rapl.rs:76:23
   5: <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::get_topology
             at ./src/sensors/powercap_rapl.rs:112:24
   6: scaphandre::exporters::stdout::StdoutExporter::runner
             at ./src/exporters/stdout.rs:122:24
   7: <scaphandre::exporters::stdout::StdoutExporter as scaphandre::exporters::Exporter>::run
             at ./src/exporters/stdout.rs:19:9
   8: scaphandre::run
             at ./src/lib.rs:74:9
   9: scaphandre::main
             at ./src/main.rs:81:5
  10: core::ops::function::FnOnce::call_once
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Reloading the rapl kernel modules, and restarting the machine does not seem to change anything.

## To Reproduce

```
cargo build
./target/debug/scaphandre stdout
```

## Expected behavior

Something should happen :) 

## Environment

Linux Distribution: Ubuntu 18.04.5 LTS
Linux Kernel: 5.14.15-051415-generic (Also had issues with 5.04)

```
>> lsmod | grep rapl

intel_rapl_msr         20480  0
intel_rapl_common      24576  1 intel_rapl_msr
rapl                   20480  0
```

```
>> ls /sys/class/powercap
dtpm  intel-rapl  intel-rapl:0
```

```
>> lshw -short

H/W path             Device          Class          Description
===============================================================
                                     system         System Product Name
/0                                   bus            WS X299 SAGE
/0/1                                 memory         64KiB BIOS
/0/4a                                memory         System Memory
/0/4a/0                              memory         16GiB DIMM DDR4 Synchronous 2667 MHz (0.4 ns)
/0/4a/1                              memory         16GiB DIMM DDR4 Synchronous 2667 MHz (0.4 ns)
/0/4a/2                              memory         16GiB DIMM DDR4 Synchronous 2667 MHz (0.4 ns)
/0/4a/3                              memory         16GiB DIMM DDR4 Synchronous 2667 MHz (0.4 ns)
/0/54                                memory         System Memory
/0/54/0                              memory         16GiB DIMM DDR4 Synchronous 2667 MHz (0.4 ns)
/0/54/1                              memory         16GiB DIMM DDR4 Synchronous 2667 MHz (0.4 ns)
/0/54/2                              memory         16GiB DIMM DDR4 Synchronous 2667 MHz (0.4 ns)
/0/54/3                              memory         16GiB DIMM DDR4 Synchronous 2667 MHz (0.4 ns)
/0/5e                                memory         896KiB L1 cache
/0/5f                                memory         14MiB L2 cache
/0/60                                memory         19MiB L3 cache
/0/61                                processor      Intel(R) Core(TM) i9-9940X CPU @ 3.30GHz
/0/2                                 memory
/0/3                                 memory
/0/100                               bridge         Sky Lake-E DMI3 Registers
/0/100/4                             generic        Sky Lake-E CBDMA Registers
/0/100/4.1                           generic        Sky Lake-E CBDMA Registers
/0/100/4.2                           generic        Sky Lake-E CBDMA Registers
/0/100/4.3                           generic        Sky Lake-E CBDMA Registers
/0/100/4.4                           generic        Sky Lake-E CBDMA Registers
/0/100/4.5                           generic        Sky Lake-E CBDMA Registers
/0/100/4.6                           generic        Sky Lake-E CBDMA Registers
/0/100/4.7                           generic        Sky Lake-E CBDMA Registers
/0/100/5                             generic        Sky Lake-E MM/Vt-d Configuration Registers
/0/100/5.2                           generic        Intel Corporation
/0/100/5.4                           generic        Intel Corporation
/0/100/8                             generic        Sky Lake-E Ubox Registers
/0/100/8.1                           generic        Sky Lake-E Ubox Registers
/0/100/8.2                           generic        Sky Lake-E Ubox Registers
/0/100/14                            bus            200 Series/Z370 Chipset Family USB 3.0 xHCI Controller
/0/100/14/0          usb1            bus            xHCI Host Controller
/0/100/14/0/e                        input          AURA Custom Human interface
/0/100/14/1          usb2            bus            xHCI Host Controller
/0/100/14.2                          generic        200 Series PCH Thermal Subsystem
/0/100/16                            communication  200 Series PCH CSME HECI #1
/0/100/17                            storage        200 Series PCH SATA controller [AHCI mode]
/0/100/1b                            bridge         200 Series PCH PCI Express Root Port #17
/0/100/1b.4                          bridge         200 Series PCH PCI Express Root Port #21
/0/100/1b.4/0                        storage        NVMe SSD Controller SM981/PM981
/0/100/1b.4/0/0      /dev/nvme0      storage        Samsung SSD 970 EVO Plus 2TB
/0/100/1b.4/0/0/1    /dev/nvme0n1    disk           2TB NVMe namespace
/0/100/1b.4/0/0/1/1                  volume         511MiB Windows FAT volume
/0/100/1b.4/0/0/1/2  /dev/nvme0n1p2  volume         1862GiB EXT4 volume
/0/100/1c                            bridge         200 Series PCH PCI Express Root Port #1
/0/100/1c.2                          bridge         200 Series PCH PCI Express Root Port #3
/0/100/1c.2/0        enp4s0          network        I210 Gigabit Network Connection
/0/100/1d                            bridge         200 Series PCH PCI Express Root Port #9
/0/100/1d/0                          bus            ASMedia Technology Inc.
/0/100/1d/0/0        usb3            bus            xHCI Host Controller
/0/100/1d/0/1        usb4            bus            xHCI Host Controller
/0/100/1d.2                          bridge         200 Series PCH PCI Express Root Port #11
/0/100/1d.2/0                        bus            ASMedia Technology Inc.
/0/100/1d.2/0/0      usb5            bus            xHCI Host Controller
/0/100/1d.2/0/1      usb6            bus            xHCI Host Controller
/0/100/1f                            bridge         X299 Chipset LPC/eSPI Controller
/0/100/1f.2                          memory         Memory controller
/0/100/1f.3                          multimedia     200 Series PCH HD Audio
/0/100/1f.4                          bus            200 Series/Z370 Chipset Family SMBus Controller
/0/100/1f.6          eno1            network        Ethernet Connection (2) I219-LM
/0/101                               bridge         Sky Lake-E PCI Express Root Port A
/0/101/0                             bridge         PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch
/0/101/0/8                           bridge         PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch
/0/101/0/10                          bridge         PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch
/0/4                                 generic        Intel Corporation
/0/6                                 generic        Sky Lake-E RAS Configuration Registers
/0/7                                 generic        Intel Corporation
/0/8                                 generic        Sky Lake-E CHA Registers
/0/8.1                               generic        Sky Lake-E CHA Registers
/0/8.2                               generic        Sky Lake-E CHA Registers
/0/8.3                               generic        Sky Lake-E CHA Registers
/0/8.4                               generic        Sky Lake-E CHA Registers
/0/8.5                               generic        Sky Lake-E CHA Registers
/0/8.6                               generic        Sky Lake-E CHA Registers
/0/8.7                               generic        Sky Lake-E CHA Registers
/0/9                                 generic        Sky Lake-E CHA Registers
/0/9.1                               generic        Sky Lake-E CHA Registers
/0/9.2                               generic        Sky Lake-E CHA Registers
/0/9.3                               generic        Sky Lake-E CHA Registers
/0/9.4                               generic        Sky Lake-E CHA Registers
/0/9.5                               generic        Sky Lake-E CHA Registers
/0/9.6                               generic        Sky Lake-E CHA Registers
/0/9.7                               generic        Sky Lake-E CHA Registers
/0/a                                 generic        Sky Lake-E CHA Registers
/0/11                                generic        Sky Lake-E CHA Registers
/0/e                                 generic        Sky Lake-E CHA Registers
/0/e.1                               generic        Sky Lake-E CHA Registers
/0/e.2                               generic        Sky Lake-E CHA Registers
/0/e.3                               generic        Sky Lake-E CHA Registers
/0/e.4                               generic        Sky Lake-E CHA Registers
/0/e.5                               generic        Sky Lake-E CHA Registers
/0/e.6                               generic        Sky Lake-E CHA Registers
/0/e.7                               generic        Sky Lake-E CHA Registers
/0/f                                 generic        Sky Lake-E CHA Registers
/0/f.1                               generic        Sky Lake-E CHA Registers
/0/f.2                               generic        Sky Lake-E CHA Registers
/0/f.3                               generic        Sky Lake-E CHA Registers
/0/f.4                               generic        Sky Lake-E CHA Registers
/0/f.5                               generic        Sky Lake-E CHA Registers
/0/f.6                               generic        Sky Lake-E CHA Registers
/0/f.7                               generic        Sky Lake-E CHA Registers
/0/10                                generic        Sky Lake-E CHA Registers
/0/10.1                              generic        Sky Lake-E CHA Registers
/0/1d                                generic        Sky Lake-E CHA Registers
/0/1d.1                              generic        Sky Lake-E CHA Registers
/0/1d.2                              generic        Sky Lake-E CHA Registers
/0/1d.3                              generic        Sky Lake-E CHA Registers
/0/1e                                generic        Sky Lake-E PCU Registers
/0/1e.1                              generic        Sky Lake-E PCU Registers
/0/1e.2                              generic        Sky Lake-E PCU Registers
/0/1e.3                              generic        Sky Lake-E PCU Registers
/0/1e.4                              generic        Sky Lake-E PCU Registers
/0/1e.5                              generic        Sky Lake-E PCU Registers
/0/1e.6                              generic        Sky Lake-E PCU Registers
/0/0                                 bridge         Sky Lake-E PCI Express Root Port A
/0/0/0                               bridge         PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch
/0/0/0/8                             bridge         PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch
/0/0/0/8/0                           display        NVIDIA Corporation
/0/0/0/8/0.1                         multimedia     NVIDIA Corporation
/0/0/0/8/0.2                         bus            NVIDIA Corporation
/0/0/0/8/0.2/0       usb7            bus            xHCI Host Controller
/0/0/0/8/0.2/1       usb8            bus            xHCI Host Controller
/0/0/0/8/0.3                         bus            NVIDIA Corporation
/0/0/0/10                            bridge         PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch
/0/0/0/10/0                          display        NVIDIA Corporation
/0/0/0/10/0.1                        multimedia     NVIDIA Corporation
/0/0/0/10/0.2                        bus            NVIDIA Corporation
/0/0/0/10/0.2/0      usb9            bus            xHCI Host Controller
/0/0/0/10/0.2/1      usb10           bus            xHCI Host Controller
/0/0/0/10/0.3                        bus            NVIDIA Corporation
/0/13                                generic        Intel Corporation
/0/14                                generic        Sky Lake-E RAS Configuration Registers
/0/18                                generic        Intel Corporation
/0/19                                generic        Intel Corporation
/0/1a                                generic        Intel Corporation
/0/1b                                generic        Intel Corporation
/0/1c                                generic        Intel Corporation
/0/a.2                               generic        Intel Corporation
/0/a.3                               generic        Intel Corporation
/0/a.4                               generic        Intel Corporation
/0/a.5                               generic        Intel Corporation
/0/a.6                               generic        Intel Corporation
/0/a.7                               generic        Intel Corporation
/0/b                                 generic        Intel Corporation
/0/b.1                               generic        Intel Corporation
/0/b.2                               generic        Intel Corporation
/0/b.3                               generic        Intel Corporation
/0/c                                 generic        Intel Corporation
/0/c.1                               generic        Intel Corporation
/0/c.2                               generic        Intel Corporation
/0/c.3                               generic        Intel Corporation
/0/c.4                               generic        Intel Corporation
/0/c.5                               generic        Intel Corporation
/0/c.6                               generic        Intel Corporation
/0/c.7                               generic        Intel Corporation
/0/d                                 generic        Intel Corporation
/0/d.1                               generic        Intel Corporation
/0/d.2                               generic        Intel Corporation
/0/d.3                               generic        Intel Corporation
/0/5                                 generic        Intel Corporation
/0/5.2                               generic        Sky Lake-E RAS Configuration Registers
/0/5.4                               generic        Intel Corporation
/0/12                                generic        Sky Lake-E M3KTI Registers
/0/12.1                              generic        Sky Lake-E M3KTI Registers
/0/12.2                              generic        Sky Lake-E M3KTI Registers
/0/15                                generic        Sky Lake-E M2PCI Registers
/0/16                                generic        Sky Lake-E M2PCI Registers
/0/16.4                              generic        Sky Lake-E M2PCI Registers
/0/17                                generic        Sky Lake-E M2PCI Registers
/0/1f                scsi3           storage
/0/1f/0.0.0          /dev/sda        disk           8001GB ST8000DM004-2CX1
/0/20                scsi5           storage
/0/20/0.0.0          /dev/sdb        disk           8001GB ST8000DM004-2CX1
/0/21                scsi7           storage
/0/21/0.0.0          /dev/sdc        disk           8001GB ST8000DM004-2CX1
/1                                   power          To Be Filled By O.E.M.
```

**Comment by bpetit** [comment]
Hi ! Thanks for noticing this bug.

What I see in the details you provided makes me think you are running kind or a "new" version of powercap: https://docs.kernel.org/power/powercap/dtpm.html

You have an extra "dtpm" forlder but no RAPL domain-specific folder under intel-rapl:0 (in mainstream cases you get 0:0, :0:1 :0:2 for example).

We need to investigate this, as we have never seen this mode running on other machines. I guess this is related to your pretty recent cpu (i9) too.

**Comment by DavidMChan** [comment]
Thanks for the reply! Let me know if we can do anything to help. I've also linked a gist of the full folder structure for /sys/class/powercap - which may be helpful in debugging.

https://gist.github.com/DavidMChan/21037f7a126f0e6a112ab691785f0e51

**Comment by jules-delecour-dav** [comment]
Hey
I got the same issue with Intel Xeon Gold proc and Fedora CoreOS sys (working on OKD4 with OVH Cloud)

````
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz
````

````
[root@worker-0 5.12.7-300.fc34.x86_64]# podman run -v /sys/class/powercap:/sys/class/powercap -v /proc:/proc -ti hubblo/scaphandre --vm stdout -t 15
scaphandre::sensors::powercap_rapl: Powercap_rapl path is: /var/scaphandre
Scaphandre stdout exporter
Sending ⚡ metrics
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/sensors/powercap_rapl.rs:76:53`
````
````
[root@worker-0 powercap]# pwd
/sys/class/powercap
[root@worker-0 powercap]# ls
dtpm
````
````
[root@worker-0 powercap]# lsmod | grep intel_rapl
intel_rapl_msr         20480  0
intel_rapl_common      28672  1 intel_rapl_msr
````

**Comment by bpetit** [comment]
Thanks for noticing, I'll push info on this thread when there is something new.

**Comment by jules-delecour-dav** [comment]
Hey, did you manage for this issue ? I can provide you more infos or we can program a workshop in order to investigate

**Comment by bpetit** [comment]
Hi @DavidMChan, @jules-delecour-dav.

I should be able to work on this issue in february. The issue I'll quickly run into is that I don't have access to any machine with an i9 or equivalent cpu. Would you be able to share a remote access to a server or desktop with those caracteristics to help troubleshoot ? (so, probably for february, then)

Thanks

**Comment by DavidMChan** [comment]
Hi @bpetit  - do you have time to add a quick outline of what needs to be done? (i.e. where I should start looking to adjust the ingestion of the data, and what needs to be updated...) If so, I can take a look at creating a PR for this issue which might be a bit easier than trying to get you access to one of our machines.

**Comment by bpetit** [comment]
Hi ! Of course. The first thing to do would surely be to :

1. find if the intel_rapl and intel_rapl_msr modules are available on recent kernels
   (seems to be appropriate to test on 5.12 and above)
2. if they are working properly on i9
3. if they are still providing data in /sys/class/powercap folder
4. if one of those 3 conditions are not met, document it, so that we find another way to make scaphandre work on i9 or equivalent cpus (maybe #78 or #

A great extra would be to provide some docs for #137 in the mean time, as you will propably go through the steps required to be documented.

Just as a reference #140 seems related, in some way.

**Comment by jules-delecour-dav** [comment]
Hi @bpetit, i can create a vm and give you access to it
I'll send you connexion access when it will be created

**Comment by pingenglj** [comment]
Hi, hitting the same issue (Ubuntu 20.04.3 LTS, GNU/Linux 5.13.0-28-generic x86_64).

```
Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
```

```shell
root@node:~$ lsmod | grep rapl
intel_rapl_msr         20480  0
intel_rapl_common      24576  1 intel_rapl_msr
rapl                   20480  0
```

```shell
root@node:~$ ll /sys/class/powercap
total 0
drwxr-xr-x  2 root root 0 feb  9 10:47 ./
drwxr-xr-x 85 root root 0 feb  9 10:47 ../
lrwxrwxrwx  1 root root 0 feb  9 10:47 dtpm -> ../../devices/virtual/powercap/dtpm/
lrwxrwxrwx  1 root root 0 feb  9 10:47 intel-rapl -> ../../devices/virtual/powercap/intel-rapl/
lrwxrwxrwx  1 root root 0 feb  9 14:14 intel-rapl:0 -> ../../devices/virtual/powercap/intel-rapl/intel-rapl:0/
```

Can read from `/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj` (but do not see subzone directories)
```shell
root@node:~$ cat /sys/class/powercap/intel-rapl/intel-rapl\:0/energy_uj
174924188972
```

**Comment by bpetit** [comment]
Hi !

Thanks for those informations. @pingenglj 

@jules-delecour-dav if need access to a physical machine with an i9 cpu to reproduce this error. A vm wouldn't do it. But thanks !

**Comment by SlimKhiari** [comment]
Hello @bpetit ,

I am trying to propagate metrics from my host machine (ubuntu 22.04) to my vm (also ubuntu 22.04). But when making ./scaphandre --vm prometheus, i obtain that :
scaphandre::sensors::powercap_rapl: Powercap_rapl path is: /var/scaphandre
Scaphandre prometheus exporter
Sending \u26a1 metrics
Press CTRL-C to stop scaphandre
thread 'main' panicked at 'Trick: if you are running on a vm, do not forget to use --vm parameter invoking scaphandre at the command line', src/sensors/mod.rs:263:18
stack backtrace:
   0:     0x5579f1858a36 - std::backtrace_rs::backtrace::libunwind::trace::h610d887740cf1987
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5579f1858a36 - std::backtrace_rs::backtrace::trace_unsynchronized::h5247907892598408
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5579f1858a36 - std::sys_common::backtrace::_print_fmt::h163eb591d48f053c
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5579f1858a36 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd5f6fdeadc182c0b
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5579f188b4ac - core::fmt::write::hab5e32ad139dc64f
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/core/src/fmt/mod.rs:1149:17
   5:     0x5579f184a725 - std::io::Write::write_fmt::hda56003ffc07f403
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/io/mod.rs:1697:15
   6:     0x5579f184cc60 - std::sys_common::backtrace::_print::hcad41b2400bee496
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5579f184cc60 - std::sys_common::backtrace::print::h2782dac9fb8841ed
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5579f184cc60 - std::panicking::default_hook::{{closure}}::heb06a17e9362a548
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:211:50
   9:     0x5579f184c7ee - std::panicking::default_hook::h3d84794a36de0246
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:228:9
  10:     0x5579f184d213 - std::panicking::rust_panic_with_hook::h6c9f137ff9fef51a
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:606:17
  11:     0x5579f18593a0 - std::panicking::begin_panic_handler::{{closure}}::h2877cd4e6462e1cb
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:502:13
  12:     0x5579f1858b84 - std::sys_common::backtrace::__rust_end_short_backtrace::h6f8a54cfa7a7d4a3
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x5579f184cd52 - rust_begin_unwind
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:498:5
  14:     0x5579f12a54e1 - core::panicking::panic_fmt::he8875066124331b8
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/core/src/panicking.rs:107:14
  15:     0x5579f1885ee1 - core::panicking::panic_display::hcc6252ba93313e49
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/core/src/panicking.rs:63:5
  16:     0x5579f12a55db - core::option::expect_failed::h92d1dc3d07d26094
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/core/src/option.rs:1637:5
  17:     0x5579f12b37bf - scaphandre::sensors::Topology::add_cpu_cores::h292edf12ceacb0dc
  18:     0x5579f12ef23d - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::generate_topology::ha40f60e38f4f0dd7
  19:     0x5579f12ef62d - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::get_topology::hd1f10b9842a4494a
  20:     0x5579f12fdfba - <scaphandre::exporters::prometheus::PrometheusExporter as scaphandre::exporters::Exporter>::run::h4f4fa4bdb9a727cb
  21:     0x5579f12b7c6c - scaphandre::run::hfd14dfaef5c665f1
  22:     0x5579f12a7667 - scaphandre::main::h44c89ca42efb3fb8
  23:     0x5579f12a5f43 - std::sys_common::backtrace::__rust_begin_short_backtrace::hff0c6ad7bcf5e558
  24:     0x5579f12a5f19 - std::rt::lang_start::{{closure}}::h8f69d29914e3e657
  25:     0x5579f1847c71 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd220f9373558aca3
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/core/src/ops/function.rs:259:13
  26:     0x5579f1847c71 - std::panicking::try::do_call::hce771ab8e2469e1b
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:406:40
  27:     0x5579f1847c71 - std::panicking::try::hdcd46bc7121f05a6
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:370:19
  28:     0x5579f1847c71 - std::panic::catch_unwind::h220bff361500ce4b
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panic.rs:133:14
  29:     0x5579f1847c71 - std::rt::lang_start_internal::{{closure}}::h9c7d2a04b3782841
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/rt.rs:128:48
  30:     0x5579f1847c71 - std::panicking::try::do_call::hf862adda5d81a53e
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:406:40
  31:     0x5579f1847c71 - std::panicking::try::hef41490d9308414a
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:370:19
  32:     0x5579f1847c71 - std::panic::catch_unwind::h351e79fc6ca7598f
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panic.rs:133:14
  33:     0x5579f1847c71 - std::rt::lang_start_internal::h039e34ac72710a33
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/rt.rs:128:20
  34:     0x5579f12a7832 - main
  35:     0x7fede17d1d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  36:     0x7fede17d1e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  37:     0x5579f12a5ac5 - _start
  38:                0x0 - <unknown>

**Comment by bpetit** [comment]
@DavidMChan would it be, by any chance, possible to access your machine for the tests (or another with the same cpu) ?

**Comment by DavidMChan** [comment]
Sure! Can you send me an email/DM, and I can work out how to get you ssh access to a machine.

**Comment by geertpingen** [comment]
Hi @bpetit , unfortunately Im still getting an exception (on branch #131), let me know if I can check/verify anything for you:

```shell
user@node:~/git/scaphandre$ sudo RUST_BACKTRACE=1 ./target/debug/scaphandre stdout -t 15
Scaphandre stdout exporter
Sending ⚡ metrics
thread 'main' panicked at 'Trick: if you are running on a vm, do not forget to use --vm parameter invoking scaphandre at the command line', src/sensors/mod.rs:263:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic_display
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:63:5
   3: core::option::expect_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/option.rs:1637:5
   4: core::option::Option<T>::expect
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/option.rs:709:21
   5: scaphandre::sensors::Topology::add_cpu_cores
             at ./src/sensors/mod.rs:259:26
   6: <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::generate_topology
             at ./src/sensors/powercap_rapl.rs:106:9
   7: <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::get_topology
             at ./src/sensors/powercap_rapl.rs:112:24
   8: scaphandre::exporters::stdout::StdoutExporter::runner
             at ./src/exporters/stdout.rs:121:24
   9: <scaphandre::exporters::stdout::StdoutExporter as scaphandre::exporters::Exporter>::run
             at ./src/exporters/stdout.rs:19:9
  10: scaphandre::run
             at ./src/lib.rs:74:9
  11: scaphandre::main
             at ./src/main.rs:81:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bpetit** [comment]
@geertpingen Hi, thanks for the feedback.

Are you running on a physical machine ? and built https://github.com/hubblo-org/scaphandre/pull/198 ?

Thanks

**Comment by geertpingen** [comment]
Hi @bpetit, you are too fast :smile:  I was too quick and pulled the wrong branch, it seems to work on first observation!
```shell
user@node:~/git/scaphandre$ sudo RUST_BACKTRACE=1 ./target/debug/scaphandre stdout -t 15
Scaphandre stdout exporter
Sending ⚡ metrics
scaphandre::sensors::powercap_rapl: Couldn't find domain folders from powercap. Fallback on socket folders.
scaphandre::sensors::powercap_rapl: Scaphandre will not be able to provide per-domain data.
Measurement step is: 2s
Host:   0 W
Top 5 consumers:
Power           PID     Exe
No processes found yet or filter returns no value.
------------------------------------------------------------

Host:   29.331151 W
Socket0 29.331152 W |

Top 5 consumers:
Power           PID     Exe
1.676065 W      918     "gitlab-runner"
0.838032 W      14      "rcu_sched"
0.838032 W      780     "systemd-resolve"
0 W     1       "systemd"
0 W     2       "kthreadd"
```

**Comment by bpetit** [comment]
Great, thanks for the feedback ! Happy testing !

**Comment by bpetit** [comment]
A new fresh test of #198 on @DavidMChan's machine seems to work properly with stdout and prometheus exporters.

**Comment by DavidMChan** [comment]
Thanks @bpetit  - This seems to be working on our other machines as well! (Sorry for the delayed test!)

**Comment by bpetit** [comment]
Thank you for the feedback !
