### ISSUE TITLE
thread 'main' panicked at 'Trick: if you are running on a vm, do not forget to use --vm parameter invoking scaphandre at the command line', src/sensors/mod.rs:263:18

### ISSUE THREAD

**Issue by SlimKhiari** [hubblo-org/scaphandre#172]

**Comment by SlimKhiari** [comment]
Hello,
After making that ./scaphandre --vm prometheus, i obtain that 
stack backtrace:
   0:     0x5556074b3a36 - std::backtrace_rs::backtrace::libunwind::trace::h610d887740cf1987
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5556074b3a36 - std::backtrace_rs::backtrace::trace_unsynchronized::h5247907892598408
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5556074b3a36 - std::sys_common::backtrace::_print_fmt::h163eb591d48f053c
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5556074b3a36 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd5f6fdeadc182c0b
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5556074e64ac - core::fmt::write::hab5e32ad139dc64f
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/core/src/fmt/mod.rs:1149:17
   5:     0x5556074a5725 - std::io::Write::write_fmt::hda56003ffc07f403
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/io/mod.rs:1697:15
   6:     0x5556074a7c60 - std::sys_common::backtrace::_print::hcad41b2400bee496
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5556074a7c60 - std::sys_common::backtrace::print::h2782dac9fb8841ed
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5556074a7c60 - std::panicking::default_hook::{{closure}}::heb06a17e9362a548
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:211:50
   9:     0x5556074a77ee - std::panicking::default_hook::h3d84794a36de0246
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:228:9
  10:     0x5556074a8213 - std::panicking::rust_panic_with_hook::h6c9f137ff9fef51a
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:606:17
  11:     0x5556074b43a0 - std::panicking::begin_panic_handler::{{closure}}::h2877cd4e6462e1cb
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:502:13
  12:     0x5556074b3b84 - std::sys_common::backtrace::__rust_end_short_backtrace::h6f8a54cfa7a7d4a3
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x5556074a7d52 - rust_begin_unwind
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:498:5
  14:     0x555606f004e1 - core::panicking::panic_fmt::he8875066124331b8
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/core/src/panicking.rs:107:14
  15:     0x5556074e0ee1 - core::panicking::panic_display::hcc6252ba93313e49
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/core/src/panicking.rs:63:5
  16:     0x555606f005db - core::option::expect_failed::h92d1dc3d07d26094
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/core/src/option.rs:1637:5
  17:     0x555606f0e7bf - scaphandre::sensors::Topology::add_cpu_cores::h292edf12ceacb0dc
  18:     0x555606f4a23d - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::generate_topology::ha40f60e38f4f0dd7
  19:     0x555606f4a62d - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::get_topology::hd1f10b9842a4494a
  20:     0x555606f58fba - <scaphandre::exporters::prometheus::PrometheusExporter as scaphandre::exporters::Exporter>::run::h4f4fa4bdb9a727cb
  21:     0x555606f12c6c - scaphandre::run::hfd14dfaef5c665f1
  22:     0x555606f02667 - scaphandre::main::h44c89ca42efb3fb8
  23:     0x555606f00f43 - std::sys_common::backtrace::__rust_begin_short_backtrace::hff0c6ad7bcf5e558
  24:     0x555606f00f19 - std::rt::lang_start::{{closure}}::h8f69d29914e3e657
  25:     0x5556074a2c71 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd220f9373558aca3
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/core/src/ops/function.rs:259:13
  26:     0x5556074a2c71 - std::panicking::try::do_call::hce771ab8e2469e1b
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:406:40
  27:     0x5556074a2c71 - std::panicking::try::hdcd46bc7121f05a6
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:370:19
  28:     0x5556074a2c71 - std::panic::catch_unwind::h220bff361500ce4b
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panic.rs:133:14
  29:     0x5556074a2c71 - std::rt::lang_start_internal::{{closure}}::h9c7d2a04b3782841
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/rt.rs:128:48
  30:     0x5556074a2c71 - std::panicking::try::do_call::hf862adda5d81a53e
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:406:40
  31:     0x5556074a2c71 - std::panicking::try::hef41490d9308414a
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panicking.rs:370:19
  32:     0x5556074a2c71 - std::panic::catch_unwind::h351e79fc6ca7598f
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/panic.rs:133:14
  33:     0x5556074a2c71 - std::rt::lang_start_internal::h039e34ac72710a33
                               at /build/rustc-oOlesr/rustc-1.58.1+dfsg1~ubuntu1/library/std/src/rt.rs:128:20
  34:     0x555606f02832 - main
  35:     0x7fdb6af78d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  36:     0x7fdb6af78e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  37:     0x555606f00ac5 - _start
  38:                0x0 - <unknown>
I would like to know if ti is normal.

(I want to propagate metrics to my vm)
