### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` - Ubuntu 22.04.1 LTS VM

### ISSUE THREAD

**Issue by cetiberiojr** [hubblo-org/scaphandre#210]
Hi,

I followed all the issues here giving some solution to this issue, but still no success.

This are my commands and issues:
``` 
developer@dev:~/gitViews/scaphandre$ sudo apt install linux-modules-extra-$(uname -r)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
linux-modules-extra-5.15.0-47-generic is already the newest version (5.15.0-47.51).
linux-modules-extra-5.15.0-47-generic set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

developer@dev:~/gitViews/scaphandre$ modprobe intel_rapl_common

developer@dev:~/gitViews/scaphandre$ helm install scaphandre helm/scaphandre
```
After that I still got issues:
```
developer@dev:~/gitViews/scaphandre$ k logs scaphandre-q6vsg
scaphandre::sensors::powercap_rapl: Powercap_rapl path is: /var/scaphandre
Scaphandre prometheus exporter
Sending ⚡ metrics
Press CTRL-C to stop scaphandre
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/sensors/powercap_rapl.rs:76:53
stack backtrace:
   0:     0x55e1bfe53c70 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55e1bfe53c70 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55e1bfe53c70 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55e1bfe53c70 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55e1bfe76c4c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55e1bfe4d442 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55e1bfe5611d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55e1bfe5611d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55e1bfe5611d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55e1bfe55dc8 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55e1bfe56801 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55e1bfe563a9 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55e1bfe540dc - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55e1bfe56369 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55e1bfe74871 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x55e1bfe74693 - core::option::expect_none_failed::h6154dc750ae47ade
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:     0x55e1bf8a8305 - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::generate_topology::h5bc10914f1385482
  17:     0x55e1bf8a84fa - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::get_topology::h06a9dd8e7d085121
  18:     0x55e1bf8f076e - <scaphandre::exporters::prometheus::PrometheusExporter as scaphandre::exporters::Exporter>::run::h6e2bd10bfd894fcb
  19:     0x55e1bf863a06 - scaphandre::run::ha4ed5db2b42f3873
  20:     0x55e1bf8502f7 - scaphandre::main::hb3cd48c47ec910bd
  21:     0x55e1bf84e7d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c9a2d2e7724640c
  22:     0x55e1bf84e7e9 - std::rt::lang_start::{{closure}}::h829cbaf531010019
  23:     0x55e1bfe56d17 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  24:     0x55e1bfe56d17 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  25:     0x55e1bfe56d17 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  26:     0x55e1bfe56d17 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  27:     0x55e1bfe56d17 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  28:     0x55e1bf8504a2 - main
  29:     0x7efe668c9cb2 - __libc_start_main
  30:     0x55e1bf84e17a - _start
  31:                0x0 - <unknown>
```
Here some commands I saw someone asking:
```
developer@dev:~/gitViews/scaphandre$ lsmod | grep intel_rapl
intel_rapl_msr         20480  0
intel_rapl_common      40960  1 intel_rapl_msr

developer@dev:~/gitViews/scaphandre$ uname -r
5.15.0-47-generic

developer@dev:~/gitViews/scaphandre$ locate rapl
/home/developer/gitViews/scaphandre/docs_src/references/sensor-powercap_rapl.md
/home/developer/gitViews/scaphandre/src/sensors/powercap_rapl.rs
/usr/lib/modules/5.15.0-46-generic/kernel/arch/x86/events/rapl.ko
/usr/lib/modules/5.15.0-46-generic/kernel/drivers/powercap/intel_rapl_common.ko
/usr/lib/modules/5.15.0-46-generic/kernel/drivers/powercap/intel_rapl_msr.ko
/usr/lib/modules/5.15.0-46-generic/kernel/drivers/thermal/intel/int340x_thermal/processor_thermal_rapl.ko
/usr/lib/modules/5.15.0-47-generic/kernel/arch/x86/events/rapl.ko
/usr/lib/modules/5.15.0-47-generic/kernel/drivers/powercap/intel_rapl_common.ko
/usr/lib/modules/5.15.0-47-generic/kernel/drivers/powercap/intel_rapl_msr.ko
/usr/lib/modules/5.15.0-47-generic/kernel/drivers/thermal/intel/int340x_thermal/processor_thermal_rapl.ko
/usr/share/doc/m4/examples/wraplifo.m4
/usr/share/doc/m4/examples/wraplifo2.m4
/usr/src/linux-headers-5.15.0-46/include/linux/intel_rapl.h
/usr/src/linux-headers-5.15.0-47/include/linux/intel_rapl.h
/var/lib/swcatalog/icons/ubuntu-jammy-universe/48x48/calligraplan_calligraplan.png
/var/lib/swcatalog/icons/ubuntu-jammy-universe/48x48/calligraplan_calligraplanwork.png
/var/lib/swcatalog/icons/ubuntu-jammy-universe/64x64/calligraplan_calligraplan.png
/var/lib/swcatalog/icons/ubuntu-jammy-universe/64x64/calligraplan_calligraplanwork.png
```
My Ubuntu VM:
```
developer@dev:~/gitViews/scaphandre$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Someone can help me here?

**Comment by kraktus** [comment]
Error comes from here: https://github.com/hubblo-org/scaphandre/blob/50fea42ebd1f8bda9d98e8d27b348c626ed3055d/src/sensors/powercap_rapl.rs#L76

Does `/var/scaphandre` exist in your VM?

**Comment by cetiberiojr** [comment]
I don't think it's the root cause of the issue...

The `/var/scaphandre` didn't exist... I created it and still same issue.

**Comment by bpetit** [comment]
Hi,

Do you have the qemu exporter running on your hypervisor ? Is this a qemu/kvm hypervisor ?
If so, you need to follow this procedure before having a working scaphandre inside the VM itself : https://hubblo-org.github.io/scaphandre-documentation/how-to_guides/propagate-metrics-hypervisor-to-vm_qemu-kvm.html

Scaphandre needs to collect data from the bare metal machine as it mainly depends on RAPL.

If you complete this procedure the /var/scaphandre folder in the VM will be filled with useful data, then it should work.
