### ISSUE TITLE
Not able to get metrics from Virtualized Environment

### ISSUE THREAD

**Issue by enrico-nxw** [hubblo-org/scaphandre#397]
## Bug description

Hello,
I have a NUC (Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz) and I created a VM with ubuntu24.04 using KVM (libvirt). I'm not able to get measurements from the VM using "scaphandre --vm". 
I get the following error:

`ubuntu@vm:~/repo-scaphandre/target/debug$ sudo RUST_BACKTRACE=full ./scaphandre --vm stdout -t 5
scaphandre::sensors::powercap_rapl: Couldn't find domain folders from powercap. Fallback on socket folders.
scaphandre::sensors::powercap_rapl: Scaphandre will not be able to provide per-domain data.
scaphandre::sensors::powercap_rapl: Could'nt find any RAPL PKG domain (nor psys).
scaphandre::sensors: Sysinfo sees 2
thread 'main' panicked at src/sensors/mod.rs:303:53:
Trick: if you are running on a vm, do not forget to use --vm parameter invoking scaphandre at the command line
stack backtrace:
   0:     0x6437f6bc76fa - std::backtrace_rs::backtrace::libunwind::trace::h99efb0985cae5d78
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x6437f6bc76fa - std::backtrace_rs::backtrace::trace_unsynchronized::he2c1aa63b3f7fad8
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x6437f6bc76fa - std::sys::backtrace::_print_fmt::h8a221d40f5e0f88b
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:66:9
   3:     0x6437f6bc76fa - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:39:26
   4:     0x6437f6beef5b - core::fmt::rt::Argument::fmt::h5da9c218ec984eaf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/rt.rs:177:76
   5:     0x6437f6beef5b - core::fmt::write::hf5713710ce10ff22
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/mod.rs:1178:21
   6:     0x6437f6bc4143 - std::io::Write::write_fmt::hda708db57927dacf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/io/mod.rs:1823:15
   7:     0x6437f6bc88a2 - std::sys::backtrace::BacktraceLock::print::hbcdbec4d97c91528
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:42:9
   8:     0x6437f6bc88a2 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:266:22
   9:     0x6437f6bc850e - std::panicking::default_hook::h81c8cd2e7c59ee33
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:293:9
  10:     0x6437f6bc912f - std::panicking::rust_panic_with_hook::had2118629c312a4a
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:797:13
  11:     0x6437f6bc8e17 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:671:13
  12:     0x6437f6bc7bd9 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:170:18
  13:     0x6437f6bc8aa4 - rust_begin_unwind
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
  14:     0x6437f5cd7fe3 - core::panicking::panic_fmt::h3eea515d05f7a35e
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
  15:     0x6437f5cd7fab - core::panicking::panic_display::h43c6507275b9b865
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:264:5
  16:     0x6437f5cd7fab - core::option::expect_failed::h6d726c0eb3b486db
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:2025:5
  17:     0x6437f5cff522 - core::option::Option<T>::expect::h3dd85dfbe342ccaa
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:928:21
  18:     0x6437f5dde379 - scaphandre::sensors::Topology::add_cpu_cores::h5fb4a4a3c2c35f49
                               at /home/ubuntu/scaphandre/src/sensors/mod.rs:303:28
  19:     0x6437f5d039a8 - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::generate_topology::h8c69cc8fc64aea6f
                               at /home/ubuntu/scaphandre/src/sensors/powercap_rapl.rs:286:9
  20:     0x6437f5d06af0 - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::get_topology::hbacb983c7e2462b8
                               at /home/ubuntu/scaphandre/src/sensors/powercap_rapl.rs:292:24
  21:     0x6437f5daf9d8 - scaphandre::exporters::stdout::StdoutExporter::new::he68d05cbca21634e
                               at /home/ubuntu/scaphandre/src/exporters/stdout.rs:88:20
  22:     0x6437f5cd9e59 - scaphandre::build_exporter::hfc10533acadc8382
                               at /home/ubuntu/scaphandre/src/main.rs:247:22
  23:     0x6437f5cd9c6a - scaphandre::parse_cli_and_run_exporter::h53527dcc74977a7f
                               at /home/ubuntu/scaphandre/src/main.rs:236:24
  24:     0x6437f5cd9b16 - scaphandre::main::hb6a75900ada5b16a
                               at /home/ubuntu/scaphandre/src/main.rs:228:5
  25:     0x6437f5cddebb - core::ops::function::FnOnce::call_once::h19a1a6ab842c33bd
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
  26:     0x6437f5ce23ce - std::sys::backtrace::__rust_begin_short_backtrace::hc0bd8f865041b007
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:154:18
  27:     0x6437f5ce2351 - std::rt::lang_start::{{closure}}::h7c82916212d2a4db
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:164:18
  28:     0x6437f6bbe420 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h08ecba131ab90ec4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:284:13
  29:     0x6437f6bbe420 - std::panicking::try::do_call::hf33a59fd8ce953f4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  30:     0x6437f6bbe420 - std::panicking::try::h5005ce80ce949fd8
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  31:     0x6437f6bbe420 - std::panic::catch_unwind::hfbae19e2e2c5b7ed
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  32:     0x6437f6bbe420 - std::rt::lang_start_internal::{{closure}}::ha0331c3690741813
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:48
  33:     0x6437f6bbe420 - std::panicking::try::do_call::hcdcbdb616b4d0295
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  34:     0x6437f6bbe420 - std::panicking::try::h3f2f1725a07d2256
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  35:     0x6437f6bbe420 - std::panic::catch_unwind::h51869e04b56b2dc3
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  36:     0x6437f6bbe420 - std::rt::lang_start_internal::h4d90db0530245041
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:20
  37:     0x6437f5ce232a - std::rt::lang_start::hc1838b47337668ed
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:163:17
  38:     0x6437f5cdde4e - main
  39:     0x7e627842a1ca - <unknown>
  40:     0x7e627842a28b - __libc_start_main
  41:     0x6437f5cd8b55 - _start
  42:                0x0 - <unknown>`

## To Reproduce

1. access the VM
2. clone the repository (https://github.com/hubblo-org/scaphandre)
3. `ubuntu@vm:~$ sudo ./scaphandre/target/debug/scaphandre --vm stdout`  // the same for prometheus

## Expected behavior

The metrics printed in stdout or exposed in http in case of prometheus

## Environment

- Ubuntu 24.04
- Linux vm 6.8.0-48-generic # 48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

## Additional context

- I executed also: `$sudo apt install linux-modules-extra-$(uname -r) && sudo modprobe intel_rapl_common` 
- The same steps works fine in the host machine. 
- In the host machine I have a scaphandre instance running as: `ubuntu@ubuntu:~/scaphandre/target/debug$ sudo ./scaphandre prometheus --qemu`
- It also not works on WLS2

**Comment by bpetit** [comment]
Hi,

did you set up a mount point for the communication between scaphandre on the host and in the vm ?

this is described here: https://hubblo-org.github.io/scaphandre-documentation/how-to_guides/propagate-metrics-hypervisor-to-vm_qemu-kvm.html

regarding WSL2: it has never been tested and surely requires multiple new developments to work, so this is unsurprising
